version: "3"
services:
  playground:
    container_name: playground
    image: afip-playground:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - afip
  scanner:
    container_name: scanner
    image: afip-scanner:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - scanner/env.list
    networks:
      - afip
  example-api:
    container_name: example-api
    image: afip-example-api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - afip
networks:
  afip: