package afip.vulns

class DefaultUrlMappings extends Vuln{

    static String getName(){
        return "Default mappings"
    }

    DefaultUrlMappings(String filePath, int lineNumber, String code){
        super(filePath, lineNumber, code)
        setIsVuln(false)
        setReason("This exposes all controllers to the public and could be a potential entry point for an attacker")
        setSolution("Delete the default url mapping generated by grails")
        setConfidence("high")
        setFriendlyName("Default mappings")
        setCriticality("medium")
        setInformation("This makes every controller in you application public.\n" +
                "This may lead internal or test controllers exposed to the internet.\n" +
                "Explicitly whitelist controllers which should be public.\n")
    }
}
